src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="users")
 */
class User implements UserInterface
{
    /**
     * @var Uuid
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=128, nullable=false, unique=true)
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=128, nullable=false)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=128, nullable=false)
     */
    private $lastname;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=61, nullable=false)
     */
    private $password;

    /**
     * @var array
     *
     * @ORM\Column(name="roles", type="json_array", nullable=false)
     */
    private $roles;

    /**
     * @param string $username
     * @param string $password
     * @param string $firstname
     * @param string $lastname
     * @param array  $roles
     */
    public function __construct(
        string $username,
        string $password,
        string $firstname,
        string $lastname,
        array $roles = []
    ) {
        $this->username = $username;
        $this->password = $password;
        $this->roles = $roles;
        $this->firstname = $firstname;
        $this->lastname = $lastname;
    }

    /**
     * @return Uuid
     */
    public function getId(): Uuid
    {
        return $this->id;
    }

    /**
     * @return array
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    /**
     * @return string
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * @return null|string
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @return null|string
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * return null
     */
    public function eraseCredentials(): void
    {
    }

    /**
     * @return string
     */
    public function getFirstname(): string
    {
        return $this->firstname;
    }

    /**
     * @return string
     */
    public function getLastname(): string
    {
        return $this->lastname;
    }

    /**
     * @return string
     */
    public function getFullName(): string
    {
        return sprintf('%s %s', $this->getFirstname(), $this->getLastname());
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Domain\Command\CreateOrderCommand;
use App\Form\CreateOrderForm;
use App\Form\Model\CreateOrderFormModel;
use App\Repository\OrderRepository;
use Ramsey\Uuid\Uuid;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\PropertyAccess\Exception\InvalidPropertyPathException;
use Symfony\Component\Routing\Annotation\Route;

class CustomerController extends AbstractController
{
    /**
     * @var OrderRepository
     */
    private $orderRepository;

    /**
     * @var MessageBusInterface
     */
    private $messageBus;

    /**
     * @param OrderRepository     $orderRepository
     * @param MessageBusInterface $messageBus
     */
    public function __construct(OrderRepository $orderRepository, MessageBusInterface $messageBus)
    {
        $this->orderRepository = $orderRepository;
        $this->messageBus = $messageBus;
    }

    /**
     * @return Response
     *
     * @Route("/customer", name="customer_index")
     */
    public function index()
    {
        return $this->render('customer/index.html.twig');
    }

    /**
     * @return Response
     *
     * @Route("/customer/orders", name="customer_orders")
     */
    public function orders()
    {
        $orders = $this->orderRepository->findBy(['reporter' => $this->getUser()], ['createdAt' => 'DESC']);

        return $this->render('customer/orders.html.twig', ['orders' => $orders]);
    }

    /**
     * @return Response
     *
     * @Route("/customer/order/{id}", name="customer_orders_view")
     */
    public function ordersView(string $id)
    {
        $uuid = Uuid::fromString($id);
        $order = $this->orderRepository->findOneBy(['reporter' => $this->getUser(), 'id' => $uuid]);

        return $this->render('customer/orders.view.html.twig', ['order' => $order]);
    }

    /**
     * @param Request $request
     *
     * @return Response
     *
     * @Route("/customer/orders/create", name="customer_orders_create")
     */
    public function createOrder(Request $request)
    {
        $model = new CreateOrderFormModel();
        $form = $this->createForm(CreateOrderForm::class, $model);
        $form->handleRequest($request);

        try {
            if ($form->isSubmitted() && $form->isValid()) {
                /** @var CreateOrderFormModel $data */
                $data = $form->getData();

                $deviceId = Uuid::fromString($data->device);
                $reporter = $this->getUser();

                $command = new CreateOrderCommand($deviceId, $data->type, $reporter, $data->description);
                $this->messageBus->dispatch($command);

                return $this->redirectToRoute('customer_orders');
            }
        } catch (InvalidPropertyPathException $exception) {
            dump($exception);
            die;
        } catch (\Throwable $exception) {
            dump($exception);
            die;
        }

        return $this->render('customer/orders.create.html.twig', ['form' => $form->createView()]);
    }
}

templates/customer/index.html.twig
{% extends 'customer.html.twig' %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Hi, {{ app.user.fullname }}</h1>
    </div>
{% endblock %}

templates/customer/orders.create.html.twig
{% extends "customer.html.twig" %}

{% block body %}
    <div class="justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
        <div class="row">
            <div class="col-md-12 mb-12">
                {{ form_row(form.type) }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 mb-12">
                {{ form_row(form.device) }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 mb-12">
                {{ form_row(form.description) }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 mb-12">
                {{ form_row(form.save) }}
            </div>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/customer/orders.html.twig
{% extends 'customer.html.twig' %}
{% trans_default_domain 'order' %}
{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2">My orders!</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ path('customer_orders_create') }}" class="btn btn-sm btn-outline-secondary">New order</a>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>{% trans %}type{% endtrans %}</th>
                <th>{% trans %}device{% endtrans %}</th>
                <th>{% trans %}status{% endtrans %}</th>
                <th>{% trans %}assignee{% endtrans %}</th>
                <th>{% trans %}reported{% endtrans %}</th>
            </tr>
            </thead>
            <tbody>
            {% for o in orders %}
                <tr>
                    <td><a href="{{ path('customer_orders_view', {id: o.id}) }}">{{ o.type|trans }}</a></td>
                    <td>{{ o.device.brand }} {{ o.device.model }} ({{ o.device.year }})</td>
                    <td><span class="badge badge-status-{{ o.status }}">{{ o.status|trans }}</span></td>
                    <td>{% if o.assignee is not null %}{{ o.assignee.fullName }}{% endif %}</td>
                    <td>{{ o.createdAt|date("F jS \\a\\t g:ia") }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/customer/orders.view.html.twig
{% extends "customer.html.twig" %}
{% trans_default_domain 'order' %}
{% block body %}
    <div class="justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ order.type|trans }}</h1>
    </div>

    <div class="row">
        <div class="col-md-9 mb-9">
            {{ order.description }}
        </div>
        <div class="col-md-3 mb-3">
            {% if order.assignee is not null %}
                <p>{% trans %}assignee{% endtrans %}: {{ order.assignee.fullName }}</p>
            {% endif %}
            <p>{% trans %}status{% endtrans %}: <span class="badge badge-status-{{ order.status }}">{{ order.status|trans }}</span></p>
            <p>{% trans %}device{% endtrans %}: {{ order.device.brand }} {{ order.device.model }} ({{ order.device.year }})</p>
            <p>{% trans %}reported{% endtrans %}: {{ order.createdAt|date("F jS \\a\\t g:ia") }}</p>
            <p>{% trans %}updated{% endtrans %}: {{ order.updatedAt|date("F jS \\a\\t g:ia") }}</p>
        </div>
    </div>
{% endblock %}